-- AlterEnum ActivityBonusType
ALTER TYPE "ActivityBonusType" ADD VALUE IF NOT EXISTS 'INR_RECHARGE_BONUS';
ALTER TYPE "ActivityBonusType" ADD VALUE IF NOT EXISTS 'USDT_RECHARGE_BONUS';

-- AlterTable Config
ALTER TABLE "Config" ADD COLUMN IF NOT EXISTS "inrDepositBonusPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Config" ADD COLUMN IF NOT EXISTS "usdtDepositBonusPercent" DOUBLE PRECISION NOT NULL DEFAULT 5;
