import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";

import { prisma, Prisma } from "@bcwin/db";
import Logger from "@bcwin/logger";
import { apiError, CommonResponses } from "@/lib/utils";
import { HTTP_STATUS } from "@/lib/http";
import { authCookie } from "@/schemas";
import { Cache, CacheKey } from "@bcwin/cache";
import { REAL_USER_WHERE } from "@/lib/realUserFilter";
import {
    firstOfIstMonth,
    istInclusiveDay,
    istInclusiveRange,
    mondayOfIstWeek,
    shiftYmdIst,
    ymdIst,
} from "@/lib/istDate";

const logger = new Logger("admin-top-performance");

// Date filter type
const timeFilterSchema = z
    .enum(["all_time", "today", "yesterday", "this_week", "this_month", "this_year"])
    .openapi({
        description: "Time filter for top performance data",
        example: "all_time",
    });

// Mode filter type
const modeSchema = z
    .enum(["all", "players", "teams"])
    .openapi({
        description: "Ranking mode: all, players (personal), or teams (including downlinks)",
        example: "all",
    });

// Date range utility functions
function getDateRange(filter: string): { start: Date | null; end: Date } {
    const today = ymdIst();
    switch (filter) {
        case "today":
            return { ...istInclusiveDay(today) };
        case "yesterday":
            return { ...istInclusiveDay(shiftYmdIst(today, -1)) };
        case "this_week":
            return { ...istInclusiveRange(mondayOfIstWeek(), today) };
        case "this_month":
            return { ...istInclusiveRange(firstOfIstMonth(today), today) };
        case "this_year":
            return { ...istInclusiveRange(`${today.slice(0, 4)}-01-01`, today) };
        case "all_time":
        default:
            return { start: null, end: new Date() };
    }
}

// Top performer schema
const topPerformerSchema = z.object({
    userId: z.string().openapi({
        description: "User ID",
        example: "uuid-123",
    }),
    username: z.string().openapi({
        description: "Player username",
        example: "player123",
    }),
    mobile: z.string().openapi({
        description: "Player mobile number",
        example: "9876543210",
    }),
    status: z.string().openapi({
        description: "Player status (active/banned)",
        example: "active",
    }),
    // Personal metrics
    totalDeposits: z.number().openapi({
        description: "Personal total deposits",
        example: 50000.0,
    }),
    totalWithdrawals: z.number().openapi({
        description: "Personal total withdrawals",
        example: 30000.0,
    }),
    totalBets: z.number().openapi({
        description: "Personal total number of bets",
        example: 1500,
    }),
    totalBetAmount: z.number().openapi({
        description: "Personal total bet amount (turnover)",
        example: 75000.0,
    }),
    totalWon: z.number().openapi({
        description: "Personal total amount won",
        example: 55000.0,
    }),
    bettingActivity: z.number().openapi({
        description: "Personal total number of bets (alias for totalBets)",
        example: 1500,
    }),
    currentBalance: z.number().openapi({
        description: "Current wallet balance",
        example: 10000.0,
    }),
    avgBetSize: z.number().openapi({
        description: "Average bet size",
        example: 50.0,
    }),
    activityScore: z.number().openapi({
        description: "Activity score (composite metric 0-100)",
        example: 85.5,
    }),
    retentionRate: z.number().openapi({
        description: "Retention rate percentage",
        example: 75.5,
    }),
    netProfit: z.number().openapi({
        description: "Personal net profit for platform (betAmount - wonAmount)",
        example: 20000.0,
    }),
    winRate: z.number().openapi({
        description: "Personal win rate percentage",
        example: 65.5,
    }),
    roi: z.number().openapi({
        description: "Personal return on investment percentage",
        example: 26.67,
    }),
    // Team / Downlink metrics (Layers 1-6)
    directDownlinksCount: z.number().openapi({
        description: "Count of direct (layer 1) referrals",
        example: 5,
    }),
    totalTeamSize: z.number().openapi({
        description: "Total team network size across layers 1–6",
        example: 25,
    }),
    teamTurnover: z.number().openapi({
        description: "Total betting turnover generated by downlink team",
        example: 150000.0,
    }),
    teamDeposits: z.number().openapi({
        description: "Total successful deposits by downlink team",
        example: 80000.0,
    }),
    teamWithdrawals: z.number().openapi({
        description: "Total successful withdrawals by downlink team",
        example: 40000.0,
    }),
    teamBets: z.number().openapi({
        description: "Total bets placed by downlink team",
        example: 3200,
    }),
    totalCombinedTurnover: z.number().openapi({
        description: "Combined turnover (personal + team downlinks)",
        example: 225000.0,
    }),
    totalCombinedDeposits: z.number().openapi({
        description: "Combined deposits (personal + team downlinks)",
        example: 130000.0,
    }),
});

// Card items schema
const cardItemsSchema = z.object({
    totalDeposits: z.number().openapi({
        description: "Total personal deposits of top performers",
        example: 150000.0,
    }),
    totalWithdrawals: z.number().openapi({
        description: "Total personal withdrawals of top performers",
        example: 80000.0,
    }),
    totalBets: z.number().openapi({
        description: "Total personal number of bets of top performers",
        example: 4500,
    }),
    totalTurnover: z.number().openapi({
        description: "Total personal betting turnover of top performers",
        example: 250000.0,
    }),
    averageROI: z.number().openapi({
        description: "Average ROI of top performers",
        example: 15.5,
    }),
    avgWinRate: z.number().openapi({
        description: "Average win rate of top performers",
        example: 65.5,
    }),
    netProfit: z.number().openapi({
        description: "Total net profit from top performers",
        example: 45000.0,
    }),
    totalTeamTurnover: z.number().optional().openapi({
        description: "Total team downlink turnover",
        example: 500000.0,
    }),
    totalTeamDeposits: z.number().optional().openapi({
        description: "Total team downlink deposits",
        example: 250000.0,
    }),
    totalTeamMembers: z.number().optional().openapi({
        description: "Total downlink team members",
        example: 120,
    }),
});

// Main top performance response schema
const topPerformanceResponseSchema = z.object({
    success: z.boolean().openapi({
        description: "Whether the request was successful",
        example: true,
    }),
    data: z.object({
        timeFilter: z.string().openapi({
            description: "Applied time filter",
            example: "all_time",
        }),
        mode: z.string().openapi({
            description: "Applied ranking mode (all, players, teams)",
            example: "all",
        }),
        cardItems: cardItemsSchema,
        topPerformers: z.array(topPerformerSchema),
    }),
});

const getTopPerformanceRoute = createRoute({
    method: "get",
    path: "/",
    tags: ["admin"],
    summary: "Get top performing players and teams",
    description:
        "Get top performing players and teams with time filters (all time, today, yesterday, this week, this month, this year) including personal metrics, downlink team metrics, card items and rankings",
    request: {
        query: z.object({
            timeFilter: timeFilterSchema.optional().default("all_time"),
            mode: modeSchema.optional().default("all"),
        }),
        cookies: authCookie,
    },
    responses: {
        200: {
            content: {
                "application/json": {
                    schema: topPerformanceResponseSchema,
                },
            },
            description: "Top performance data retrieved successfully",
        },
        ...CommonResponses.badRequest(),
        ...CommonResponses.unauthorized(),
        ...CommonResponses.internalServerError(),
    },
});

type TopPerformanceData = z.infer<typeof topPerformanceResponseSchema>["data"];

export const topPerformanceRoutes = (app: OpenAPIHono) => {
    app.openapi(getTopPerformanceRoute, async (c) => {
        try {
            const { timeFilter, mode } = c.req.valid("query");
            const dateRange = getDateRange(timeFilter);

            // Check cache
            const cacheKey = CacheKey.adminTopPerformance;
            const fieldKey = `top-perf:${timeFilter}:${mode}`;

            const cachedData = await Cache.hget<TopPerformanceData>(
                cacheKey,
                fieldKey
            );

            if (cachedData) {
                return c.json(
                    {
                        success: true,
                        data: cachedData,
                    },
                    HTTP_STATUS.OK
                );
            }

            // Build date filter for Prisma queries
            const dateFilter: Prisma.DateTimeFilter = {};
            if (dateRange.start) {
                dateFilter.gte = dateRange.start;
            }
            dateFilter.lte = dateRange.end;
            const hasDateFilter = dateRange.start !== null || dateFilter.lte !== undefined;

            // Fetch all real users
            const users = await prisma.user.findMany({
                where: REAL_USER_WHERE,
                select: {
                    id: true,
                    username: true,
                    mobileNumber: true,
                    referralCode: true,
                    referredBy: true,
                    isBanned: true,
                    balance: true,
                    createdAt: true,
                },
            });

            if (users.length === 0) {
                const emptyResult: TopPerformanceData = {
                    timeFilter,
                    mode,
                    cardItems: {
                        totalDeposits: 0,
                        totalWithdrawals: 0,
                        totalBets: 0,
                        totalTurnover: 0,
                        averageROI: 0,
                        avgWinRate: 0,
                        netProfit: 0,
                        totalTeamTurnover: 0,
                        totalTeamDeposits: 0,
                        totalTeamMembers: 0,
                    },
                    topPerformers: [],
                };
                return c.json({ success: true, data: emptyResult }, HTTP_STATUS.OK);
            }

            const betDateWhere = hasDateFilter ? { createdAt: dateFilter } : {};

            // 7 days window for retention/recency
            const sevenDaysAgo = new Date(dateRange.end);
            sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

            // Run bulk aggregations in parallel across the whole DB
            const [
                depositsGroup,
                withdrawalsGroup,
                wingoBetsGroup,
                fiveDBetsGroup,
                k3BetsGroup,
                motoBetsGroup,
                trxWingoBetsGroup,
                inoutBetsGroup,
                wingoWinsRaw,
                fiveDWinsRaw,
                k3WinsRaw,
                motoWinsRaw,
                trxWingoWinsRaw,
                inoutWinsGroup,
                recentActiveUsersRaw,
                recentWingoBetsGroup,
            ] = await Promise.all([
                // Deposits
                prisma.deposit.groupBy({
                    by: ["userId"],
                    where: {
                        status: "SUCCESS",
                        user: REAL_USER_WHERE,
                        ...(hasDateFilter ? { createdAt: dateFilter } : {}),
                    },
                    _sum: { amount: true },
                }),
                // Withdrawals
                prisma.withdraw.groupBy({
                    by: ["userId"],
                    where: {
                        status: "SUCCESS",
                        user: REAL_USER_WHERE,
                        ...(hasDateFilter ? { createdAt: dateFilter } : {}),
                    },
                    _sum: { amount: true },
                }),
                // Wingo bets
                prisma.wingoBet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        ...betDateWhere,
                    },
                    _sum: { betAmount: true },
                    _count: { _all: true },
                }),
                // 5D bets
                prisma.fiveDBet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        ...betDateWhere,
                    },
                    _sum: { betAmount: true },
                    _count: { _all: true },
                }),
                // K3 bets
                prisma.k3Bet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        ...betDateWhere,
                    },
                    _sum: { betAmount: true },
                    _count: { _all: true },
                }),
                // Moto bets
                prisma.motoBet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        ...betDateWhere,
                    },
                    _sum: { betAmount: true },
                    _count: { _all: true },
                }),
                // TRX Wingo bets
                prisma.trxWingoBet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        ...betDateWhere,
                    },
                    _sum: { betAmount: true },
                    _count: { _all: true },
                }),
                // Inout bets
                prisma.inoutBet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        ...betDateWhere,
                    },
                    _sum: { betAmount: true, winAmount: true },
                    _count: { _all: true },
                }),
                // Wins: Wingo
                prisma.$queryRaw<Array<{ userId: string; totalWin: number; winCount: number }>>(
                    Prisma.sql`
                        SELECT b."userId", COALESCE(SUM(r."winAmount"), 0)::float as "totalWin", COUNT(r.id)::int as "winCount"
                        FROM "WingoBetResult" r
                        JOIN "WingoBet" b ON r."betId" = b.id
                        JOIN "User" u ON b."userId" = u.id
                        WHERE u."isDemo" = false AND u.role = ${"USER"}::"Role" AND r."isWin" = true
                        ${hasDateFilter && dateRange.start ? Prisma.sql`AND r."processedAt" >= ${dateRange.start}` : Prisma.empty}
                        ${hasDateFilter && dateRange.end ? Prisma.sql`AND r."processedAt" <= ${dateRange.end}` : Prisma.empty}
                        GROUP BY b."userId"
                    `
                ),
                // Wins: 5D
                prisma.$queryRaw<Array<{ userId: string; totalWin: number; winCount: number }>>(
                    Prisma.sql`
                        SELECT b."userId", COALESCE(SUM(r."winAmount"), 0)::float as "totalWin", COUNT(r.id)::int as "winCount"
                        FROM "FiveDBetResult" r
                        JOIN "FiveDBet" b ON r."betId" = b.id
                        JOIN "User" u ON b."userId" = u.id
                        WHERE u."isDemo" = false AND u.role = ${"USER"}::"Role" AND r."isWin" = true
                        ${hasDateFilter && dateRange.start ? Prisma.sql`AND r."processedAt" >= ${dateRange.start}` : Prisma.empty}
                        ${hasDateFilter && dateRange.end ? Prisma.sql`AND r."processedAt" <= ${dateRange.end}` : Prisma.empty}
                        GROUP BY b."userId"
                    `
                ),
                // Wins: K3
                prisma.$queryRaw<Array<{ userId: string; totalWin: number; winCount: number }>>(
                    Prisma.sql`
                        SELECT b."userId", COALESCE(SUM(r."winAmount"), 0)::float as "totalWin", COUNT(r.id)::int as "winCount"
                        FROM "K3BetResult" r
                        JOIN "K3Bet" b ON r."betId" = b.id
                        JOIN "User" u ON b."userId" = u.id
                        WHERE u."isDemo" = false AND u.role = ${"USER"}::"Role" AND r."isWin" = true
                        ${hasDateFilter && dateRange.start ? Prisma.sql`AND r."processedAt" >= ${dateRange.start}` : Prisma.empty}
                        ${hasDateFilter && dateRange.end ? Prisma.sql`AND r."processedAt" <= ${dateRange.end}` : Prisma.empty}
                        GROUP BY b."userId"
                    `
                ),
                // Wins: Moto
                prisma.$queryRaw<Array<{ userId: string; totalWin: number; winCount: number }>>(
                    Prisma.sql`
                        SELECT b."userId", COALESCE(SUM(r."winAmount"), 0)::float as "totalWin", COUNT(r.id)::int as "winCount"
                        FROM "MotoBetResult" r
                        JOIN "MotoBet" b ON r."betId" = b.id
                        JOIN "User" u ON b."userId" = u.id
                        WHERE u."isDemo" = false AND u.role = ${"USER"}::"Role" AND r."isWin" = true
                        ${hasDateFilter && dateRange.start ? Prisma.sql`AND r."processedAt" >= ${dateRange.start}` : Prisma.empty}
                        ${hasDateFilter && dateRange.end ? Prisma.sql`AND r."processedAt" <= ${dateRange.end}` : Prisma.empty}
                        GROUP BY b."userId"
                    `
                ),
                // Wins: TRX Wingo
                prisma.$queryRaw<Array<{ userId: string; totalWin: number; winCount: number }>>(
                    Prisma.sql`
                        SELECT b."userId", COALESCE(SUM(r."winAmount"), 0)::float as "totalWin", COUNT(r.id)::int as "winCount"
                        FROM "TrxWingoBetResult" r
                        JOIN "TrxWingoBet" b ON r."betId" = b.id
                        JOIN "User" u ON b."userId" = u.id
                        WHERE u."isDemo" = false AND u.role = ${"USER"}::"Role" AND r."isWin" = true
                        ${hasDateFilter && dateRange.start ? Prisma.sql`AND r."processedAt" >= ${dateRange.start}` : Prisma.empty}
                        ${hasDateFilter && dateRange.end ? Prisma.sql`AND r."processedAt" <= ${dateRange.end}` : Prisma.empty}
                        GROUP BY b."userId"
                    `
                ),
                // Inout wins
                prisma.inoutBet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        winAmount: { gt: 0 },
                        ...betDateWhere,
                    },
                    _sum: { winAmount: true },
                    _count: { _all: true },
                }),
                // Recent active users (last 7 days)
                prisma.$queryRaw<Array<{ userId: string }>>(
                    Prisma.sql`
                        SELECT DISTINCT "userId" FROM (
                            SELECT "userId" FROM "WingoBet" WHERE "createdAt" >= ${sevenDaysAgo} AND "createdAt" <= ${dateRange.end}
                            UNION
                            SELECT "userId" FROM "FiveDBet" WHERE "createdAt" >= ${sevenDaysAgo} AND "createdAt" <= ${dateRange.end}
                            UNION
                            SELECT "userId" FROM "K3Bet" WHERE "createdAt" >= ${sevenDaysAgo} AND "createdAt" <= ${dateRange.end}
                            UNION
                            SELECT "userId" FROM "MotoBet" WHERE "createdAt" >= ${sevenDaysAgo} AND "createdAt" <= ${dateRange.end}
                            UNION
                            SELECT "userId" FROM "TrxWingoBet" WHERE "createdAt" >= ${sevenDaysAgo} AND "createdAt" <= ${dateRange.end}
                            UNION
                            SELECT "userId" FROM "InoutBet" WHERE "createdAt" >= ${sevenDaysAgo} AND "createdAt" <= ${dateRange.end}
                        ) active_sub
                    `
                ),
                // Recent wingo bets count (for activity score)
                prisma.wingoBet.groupBy({
                    by: ["userId"],
                    where: {
                        user: REAL_USER_WHERE,
                        createdAt: {
                            gte: sevenDaysAgo,
                            lte: dateRange.end,
                        },
                    },
                    _count: { _all: true },
                }),
            ]);

            // Build personal lookup maps
            const depositsMap = new Map<string, number>();
            depositsGroup.forEach((d) => depositsMap.set(d.userId, d._sum.amount ?? 0));

            const withdrawalsMap = new Map<string, number>();
            withdrawalsGroup.forEach((w) => withdrawalsMap.set(w.userId, w._sum.amount ?? 0));

            const betsCountMap = new Map<string, number>();
            const betsAmountMap = new Map<string, number>();

            const addBetData = (items: Array<{ userId: string; _count: { _all: number }; _sum: { betAmount: number | null } }>) => {
                items.forEach((b) => {
                    betsCountMap.set(b.userId, (betsCountMap.get(b.userId) ?? 0) + (b._count._all ?? 0));
                    betsAmountMap.set(b.userId, (betsAmountMap.get(b.userId) ?? 0) + (b._sum.betAmount ?? 0));
                });
            };

            addBetData(wingoBetsGroup);
            addBetData(fiveDBetsGroup);
            addBetData(k3BetsGroup);
            addBetData(motoBetsGroup);
            addBetData(trxWingoBetsGroup);
            addBetData(inoutBetsGroup);

            const winsCountMap = new Map<string, number>();
            const winsAmountMap = new Map<string, number>();

            const addWinRaw = (rows: Array<{ userId: string; totalWin: number; winCount: number }>) => {
                rows.forEach((r) => {
                    winsCountMap.set(r.userId, (winsCountMap.get(r.userId) ?? 0) + (r.winCount ?? 0));
                    winsAmountMap.set(r.userId, (winsAmountMap.get(r.userId) ?? 0) + (r.totalWin ?? 0));
                });
            };

            addWinRaw(wingoWinsRaw);
            addWinRaw(fiveDWinsRaw);
            addWinRaw(k3WinsRaw);
            addWinRaw(motoWinsRaw);
            addWinRaw(trxWingoWinsRaw);

            inoutWinsGroup.forEach((w) => {
                winsCountMap.set(w.userId, (winsCountMap.get(w.userId) ?? 0) + (w._count._all ?? 0));
                winsAmountMap.set(w.userId, (winsAmountMap.get(w.userId) ?? 0) + (w._sum.winAmount ?? 0));
            });

            const activeUserSet = new Set(recentActiveUsersRaw.map((r) => r.userId));
            const recentWingoMap = new Map<string, number>();
            recentWingoBetsGroup.forEach((b) => recentWingoMap.set(b.userId, b._count._all ?? 0));

            // Build in-memory referral tree for instant 6-layer team calculations
            const parentCodeToChildren = new Map<string, typeof users>();
            for (const u of users) {
                if (u.referredBy) {
                    if (!parentCodeToChildren.has(u.referredBy)) {
                        parentCodeToChildren.set(u.referredBy, []);
                    }
                    parentCodeToChildren.get(u.referredBy)!.push(u);
                }
            }

            // Helper to get 6-layer downlinks for any user
            const getDownlinkIds = (userRefCode: string | null, maxLayers = 6) => {
                if (!userRefCode) return { directIds: [] as string[], allIds: [] as string[] };
                const directChildren = parentCodeToChildren.get(userRefCode) || [];
                const directIds = directChildren.map((c) => c.id);
                const allIds: string[] = [...directIds];

                let currentLayer = directChildren;
                for (let l = 2; l <= maxLayers; l++) {
                    if (currentLayer.length === 0) break;
                    const nextLayer: typeof users = [];
                    for (const parent of currentLayer) {
                        const children = parentCodeToChildren.get(parent.referralCode) || [];
                        for (const child of children) {
                            allIds.push(child.id);
                            nextLayer.push(child);
                        }
                    }
                    currentLayer = nextLayer;
                }
                return { directIds, allIds };
            };

            // Compute performance metrics for all users
            const userPerformanceData = users.map((user) => {
                // Personal
                const totalDeposits = depositsMap.get(user.id) ?? 0;
                const totalWithdrawals = withdrawalsMap.get(user.id) ?? 0;
                const totalBets = betsCountMap.get(user.id) ?? 0;
                const totalBetAmount = betsAmountMap.get(user.id) ?? 0;
                const totalWinAmount = winsAmountMap.get(user.id) ?? 0;
                const totalWinningBets = winsCountMap.get(user.id) ?? 0;

                const winRate = totalBets > 0 ? (totalWinningBets / totalBets) * 100 : 0;
                const netProfit = totalBetAmount - totalWinAmount;
                const avgBetSize = totalBets > 0 ? totalBetAmount / totalBets : 0;
                const roi = totalBetAmount > 0 ? (netProfit / totalBetAmount) * 100 : 0;

                // Downlinks / Team metrics (6 layers)
                const { directIds, allIds } = getDownlinkIds(user.referralCode, 6);
                let teamTurnover = 0;
                let teamDeposits = 0;
                let teamWithdrawals = 0;
                let teamBets = 0;

                for (const memberId of allIds) {
                    teamTurnover += betsAmountMap.get(memberId) ?? 0;
                    teamDeposits += depositsMap.get(memberId) ?? 0;
                    teamWithdrawals += withdrawalsMap.get(memberId) ?? 0;
                    teamBets += betsCountMap.get(memberId) ?? 0;
                }

                const totalCombinedTurnover = totalBetAmount + teamTurnover;
                const totalCombinedDeposits = totalDeposits + teamDeposits;

                // Activity score
                const startDate = dateRange.start || user.createdAt;
                const daysSinceStart = Math.max(
                    1,
                    Math.floor((dateRange.end.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
                );

                const recentBets = recentWingoMap.get(user.id) ?? 0;
                const bettingScore = Math.min((totalBets / 1000) * 50, 50);
                const depositScore = Math.min((totalDeposits / 100000) * 30, 30);
                const recencyScore = Math.min((recentBets / 30) * 20, 20);
                const activityScore = Math.min(bettingScore + depositScore + recencyScore, 100);

                // Retention rate
                const isRecentlyActive = activeUserSet.has(user.id);
                let retentionRate = 0;
                if (isRecentlyActive) {
                    if (daysSinceStart <= 30) retentionRate = 90;
                    else if (daysSinceStart <= 90) retentionRate = 70;
                    else retentionRate = 60;
                }

                return {
                    userId: user.id,
                    username: user.username,
                    mobile: user.mobileNumber,
                    status: user.isBanned ? "banned" : "active",
                    // Personal
                    totalDeposits: Number(totalDeposits.toFixed(2)),
                    totalWithdrawals: Number(totalWithdrawals.toFixed(2)),
                    totalBets,
                    totalBetAmount: Number(totalBetAmount.toFixed(2)),
                    totalWon: Number(totalWinAmount.toFixed(2)),
                    bettingActivity: totalBets,
                    currentBalance: Number(user.balance.toFixed(2)),
                    avgBetSize: Number(avgBetSize.toFixed(2)),
                    activityScore: Number(activityScore.toFixed(2)),
                    retentionRate: Number(retentionRate.toFixed(2)),
                    netProfit: Number(netProfit.toFixed(2)),
                    winRate: Number(winRate.toFixed(2)),
                    roi: Number(roi.toFixed(2)),
                    // Downlinks
                    directDownlinksCount: directIds.length,
                    totalTeamSize: allIds.length,
                    teamTurnover: Number(teamTurnover.toFixed(2)),
                    teamDeposits: Number(teamDeposits.toFixed(2)),
                    teamWithdrawals: Number(teamWithdrawals.toFixed(2)),
                    teamBets,
                    totalCombinedTurnover: Number(totalCombinedTurnover.toFixed(2)),
                    totalCombinedDeposits: Number(totalCombinedDeposits.toFixed(2)),
                };
            });

            // Sorting based on mode
            if (mode === "teams") {
                // Rank by Team + Downlink turnover & network size
                userPerformanceData.sort((a, b) => {
                    if (b.totalCombinedTurnover !== a.totalCombinedTurnover) {
                        return b.totalCombinedTurnover - a.totalCombinedTurnover;
                    }
                    if (b.teamTurnover !== a.teamTurnover) {
                        return b.teamTurnover - a.teamTurnover;
                    }
                    if (b.totalTeamSize !== a.totalTeamSize) {
                        return b.totalTeamSize - a.totalTeamSize;
                    }
                    return b.totalCombinedDeposits - a.totalCombinedDeposits;
                });
            } else if (mode === "players") {
                // Rank strictly by Personal turnover
                userPerformanceData.sort((a, b) => {
                    if (b.totalBetAmount !== a.totalBetAmount) {
                        return b.totalBetAmount - a.totalBetAmount;
                    }
                    if (b.totalDeposits !== a.totalDeposits) {
                        return b.totalDeposits - a.totalDeposits;
                    }
                    if (b.netProfit !== a.netProfit) {
                        return b.netProfit - a.netProfit;
                    }
                    return b.totalBets - a.totalBets;
                });
            } else {
                // "all" mode: Prioritize highest overall turnover (combined personal + team) and activity
                userPerformanceData.sort((a, b) => {
                    if (b.totalCombinedTurnover !== a.totalCombinedTurnover) {
                        return b.totalCombinedTurnover - a.totalCombinedTurnover;
                    }
                    if (b.totalBetAmount !== a.totalBetAmount) {
                        return b.totalBetAmount - a.totalBetAmount;
                    }
                    if (b.totalCombinedDeposits !== a.totalCombinedDeposits) {
                        return b.totalCombinedDeposits - a.totalCombinedDeposits;
                    }
                    return b.activityScore - a.activityScore;
                });
            }

            // Take top 25 performers
            const topPerformers = userPerformanceData.slice(0, 25);

            // Calculate card items summary
            const activePerformers = topPerformers.filter(
                (p) => p.totalCombinedTurnover > 0 || p.totalCombinedDeposits > 0 || p.totalBets > 0
            );
            const baseForCards = activePerformers.length > 0 ? activePerformers : topPerformers.slice(0, 5);

            const cardItems = {
                totalDeposits: Number(
                    baseForCards.reduce((sum, p) => sum + p.totalDeposits, 0).toFixed(2)
                ),
                totalWithdrawals: Number(
                    baseForCards.reduce((sum, p) => sum + p.totalWithdrawals, 0).toFixed(2)
                ),
                totalBets: baseForCards.reduce((sum, p) => sum + p.totalBets, 0),
                totalTurnover: Number(
                    baseForCards.reduce((sum, p) => sum + p.totalBetAmount, 0).toFixed(2)
                ),
                averageROI:
                    baseForCards.length > 0
                        ? Number((baseForCards.reduce((sum, p) => sum + p.roi, 0) / baseForCards.length).toFixed(2))
                        : 0,
                avgWinRate:
                    baseForCards.length > 0
                        ? Number((baseForCards.reduce((sum, p) => sum + p.winRate, 0) / baseForCards.length).toFixed(2))
                        : 0,
                netProfit: Number(
                    baseForCards.reduce((sum, p) => sum + p.netProfit, 0).toFixed(2)
                ),
                totalTeamTurnover: Number(
                    baseForCards.reduce((sum, p) => sum + p.teamTurnover, 0).toFixed(2)
                ),
                totalTeamDeposits: Number(
                    baseForCards.reduce((sum, p) => sum + p.teamDeposits, 0).toFixed(2)
                ),
                totalTeamMembers: baseForCards.reduce((sum, p) => sum + p.totalTeamSize, 0),
            };

            const result: TopPerformanceData = {
                timeFilter,
                mode,
                cardItems,
                topPerformers,
            };

            // Cache for 60 seconds
            await Cache.hset(cacheKey, fieldKey, result, 60);

            return c.json(
                {
                    success: true,
                    data: result,
                },
                HTTP_STATUS.OK
            );
        } catch (error) {
            logger.error("Error fetching top performance data:", error);
            return apiError(
                c,
                "Internal server error",
                HTTP_STATUS.INTERNAL_SERVER_ERROR
            );
        }
    });
};
